
List flashCardData = [
  {"textUpper": "A","textLower": "a", "color": 0xff3d6db5,"letterImage":"assets/icons/letters/A.png","sound":"musics/letters/A.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/apple.png","tittle":"Apple"},
  {"textUpper": "B","textLower": "b", "color": 0xfff04822,"letterImage":"assets/icons/letters/B.png","sound":"musics/letters/B.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/ball.png","tittle":"Ball"},
  {"textUpper": "C","textLower": "c", "color": 0xffef1e3b,"letterImage":"assets/icons/letters/C.png","sound":"musics/letters/C.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/car.png","tittle":"Car"},
  {"textUpper": "D","textLower": "d", "color": 0xffc3d130,"letterImage":"assets/icons/letters/D.png","sound":"musics/letters/D.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/dog.png","tittle":"Dog"},
  {"textUpper": "E","textLower": "e", "color": 0xff73499c,"letterImage":"assets/icons/letters/E.png","sound":"musics/letters/E.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/elephant.png","tittle":"Elephant"},
  {"textUpper": "F","textLower": "f", "color": 0xffed278f,"letterImage":"assets/icons/letters/F.png","sound":"musics/letters/F.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/fox.png","tittle":"Fox"},
  {"textUpper": "G","textLower": "g", "color": 0xffea1f28,"letterImage":"assets/icons/letters/G.png","sound":"musics/letters/G.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/goat.png","tittle":"Goat"},
  {"textUpper": "H","textLower": "h", "color": 0xff37a44f,"letterImage":"assets/icons/letters/H.png","sound":"musics/letters/H.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/hat.png","tittle":"Hat"},
  {"textUpper": "I","textLower": "i", "color": 0xff4ba8e3,"letterImage":"assets/icons/letters/I.png","sound":"musics/letters/I.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/igloo.png","tittle":"Igloo"},
  {"textUpper": "J","textLower": "j", "color": 0xfff29220,"letterImage":"assets/icons/letters/J.png","sound":"musics/letters/J.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/joler.png","tittle":"Joker"},
  {"textUpper": "K","textLower": "k", "color": 0xfff5e932,"letterImage":"assets/icons/letters/K.png","sound":"musics/letters/K.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/kangaroo.png","tittle":"Kangaroo"},
  {"textUpper": "L","textLower": "l", "color": 0xff3cb24b,"letterImage":"assets/icons/letters/L.png","sound":"musics/letters/L.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/lion.png","tittle":"Lion"},
  {"textUpper": "M","textLower": "m", "color": 0xff23703b,"letterImage":"assets/icons/letters/M.png","sound":"musics/letters/M.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/mouse.png","tittle":"Mouse"},
  {"textUpper": "N","textLower": "n", "color": 0xff4aa8e1,"letterImage":"assets/icons/letters/N.png","sound":"musics/letters/N.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/nest.png","tittle":"Nest"},
  {"textUpper": "O","textLower": "o", "color": 0xffb11e79,"letterImage":"assets/icons/letters/O.png","sound":"musics/letters/O.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/owl.png","tittle":"Owl"},
  {"textUpper": "P","textLower": "p", "color": 0xff283a8e,"letterImage":"assets/icons/letters/P.png","sound":"musics/letters/P.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/pig.png","tittle":"Pig"},
  {"textUpper": "Q","textLower": "q", "color": 0xff1d1b43,"letterImage":"assets/icons/letters/Q.png","sound":"musics/letters/Q.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/queen.png","tittle":"Queen"},
  {"textUpper": "R","textLower": "r", "color": 0xff662f90,"letterImage":"assets/icons/letters/R.png","sound":"musics/letters/R.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/rabbit.png","tittle":"Rabbit"},
  {"textUpper": "S","textLower": "s", "color": 0xff9d2065,"letterImage":"assets/icons/letters/S.png","sound":"musics/letters/S.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/sun.png","tittle":"Sun"},
  {"textUpper": "T","textLower": "t", "color": 0xffd91a5d,"letterImage":"assets/icons/letters/T.png","sound":"musics/letters/T.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/train.png","tittle":"Train"},
  {"textUpper": "U","textLower": "u", "color": 0xffc1b39a,"letterImage":"assets/icons/letters/U.png","sound":"musics/letters/U.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/umbrella.png","tittle":"Umbrella"},
  {"textUpper": "V","textLower": "v", "color": 0xff6a584d,"letterImage":"assets/icons/letters/V.png","sound":"musics/letters/V.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/voiline.png","tittle":"Violin"},
  {"textUpper": "W","textLower": "w", "color": 0xff4babe1,"letterImage":"assets/icons/letters/W.png","sound":"musics/letters/W.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/whale.png","tittle":"Whale"},
  {"textUpper": "X","textLower": "x", "color": 0xffed2d7c,"letterImage":"assets/icons/letters/X.png","sound":"musics/letters/X.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/xylophone.png","tittle":"Xylophone"},
  {"textUpper": "Y","textLower": "y", "color": 0xffb6202e,"letterImage":"assets/icons/letters/Y.png","sound":"musics/letters/Y.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/yak.png","tittle":"Yak"},
  {"textUpper": "Z","textLower": "z", "color": 0xfff5e934,"letterImage":"assets/icons/letters/Z.png","sound":"musics/letters/Z.mp3","background":"assets/backgrounds/3d-view-adorable-pet-cat.jpg","iconImage":"assets/icons/img/zebra.png","tittle":"Zebra"},
];

List tochLetterData=[
  {"touchLetter": "D","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/F.png"},
  {"touchLetter": "C","img1":"assets/icons/letters/X.png","img2":"assets/icons/letters/I.png","img3":"assets/icons/letters/C.png"},
  {"touchLetter": "X","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/X.png","img3":"assets/icons/letters/F.png"},
  {"touchLetter": "M","img1":"assets/icons/letters/L.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "U","img1":"assets/icons/letters/U.png","img2":"assets/icons/letters/E.png","img3":"assets/icons/letters/W.png"},
  {"touchLetter": "P","img1":"assets/icons/letters/N.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/P.png"},
  {"touchLetter": "A","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "N","img1":"assets/icons/letters/N.png","img2":"assets/icons/letters/J.png","img3":"assets/icons/letters/Z.png"},
  {"touchLetter": "E","img1":"assets/icons/letters/E.png","img2":"assets/icons/letters/N.png","img3":"assets/icons/letters/O.png"},
  {"touchLetter": "S","img1":"assets/icons/letters/L.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/S.png"},
  {"touchLetter": "T","img1":"assets/icons/letters/O.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/P.png"},
  {"touchLetter": "B","img1":"assets/icons/letters/C.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/B.png"},
  {"touchLetter": "W","img1":"assets/icons/letters/G.png","img2":"assets/icons/letters/W.png","img3":"assets/icons/letters/K.png"},
  {"touchLetter": "I","img1":"assets/icons/letters/I.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/D.png"},
  {"touchLetter": "Q","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/Q.png","img3":"assets/icons/letters/L.png"},
  {"touchLetter": "Y","img1":"assets/icons/letters/B.png","img2":"assets/icons/letters/X.png","img3":"assets/icons/letters/Y.png"},
  {"touchLetter": "O","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/C.png","img3":"assets/icons/letters/O.png"},
  {"touchLetter": "F","img1":"assets/icons/letters/F.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/V.png"},
  {"touchLetter": "Z","img1":"assets/icons/letters/H.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/Z.png"},
  {"touchLetter": "L","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/L.png","img3":"assets/icons/letters/R.png"},
  {"touchLetter": "J","img1":"assets/icons/letters/G.png","img2":"assets/icons/letters/I.png","img3":"assets/icons/letters/J.png"},
  {"touchLetter": "V","img1":"assets/icons/letters/V.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/F.png"},
  {"touchLetter": "L","img1":"assets/icons/letters/N.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/L.png"},
  {"touchLetter": "H","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/H.png","img3":"assets/icons/letters/U.png"},
  {"touchLetter": "R","img1":"assets/icons/letters/R.png","img2":"assets/icons/letters/W.png","img3":"assets/icons/letters/T.png"},
  {"touchLetter": "J","img1":"assets/icons/letters/G.png","img2":"assets/icons/letters/S.png","img3":"assets/icons/letters/J.png"},
  {"touchLetter": "O","img1":"assets/icons/letters/O.png","img2":"assets/icons/letters/X.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "L","img1":"assets/icons/letters/K.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/L.png"},
  {"touchLetter": "S","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/F.png"},
  {"touchLetter": "H","img1":"assets/icons/letters/O.png","img2":"assets/icons/letters/H.png","img3":"assets/icons/letters/S.png"},
  {"touchLetter": "C","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/B.png","img3":"assets/icons/letters/C.png"},
  {"touchLetter": "Y","img1":"assets/icons/letters/Y.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/K.png"},
  {"touchLetter": "A","img1":"assets/icons/letters/F.png","img2":"assets/icons/letters/D.png","img3":"assets/icons/letters/A.png"},
  {"touchLetter": "K","img1":"assets/icons/letters/K.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "E","img1":"assets/icons/letters/V.png","img2":"assets/icons/letters/E.png","img3":"assets/icons/letters/G.png"},
  {"touchLetter": "W","img1":"assets/icons/letters/I.png","img2":"assets/icons/letters/K.png","img3":"assets/icons/letters/W.png"},
  {"touchLetter": "M","img1":"assets/icons/letters/M.png","img2":"assets/icons/letters/L.png","img3":"assets/icons/letters/J.png"},
  {"touchLetter": "U","img1":"assets/icons/letters/G.png","img2":"assets/icons/letters/U.png","img3":"assets/icons/letters/N.png"},
  {"touchLetter": "D","img1":"assets/icons/letters/O.png","img2":"assets/icons/letters/Q.png","img3":"assets/icons/letters/D.png"},
  {"touchLetter": "F","img1":"assets/icons/letters/F.png","img2":"assets/icons/letters/B.png","img3":"assets/icons/letters/R.png"},
  {"touchLetter": "T","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "I","img1":"assets/icons/letters/I.png","img2":"assets/icons/letters/X.png","img3":"assets/icons/letters/K.png"},
  {"touchLetter": "N","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/P.png","img3":"assets/icons/letters/N.png"},
  {"touchLetter": "V","img1":"assets/icons/letters/V.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/R.png"},
  {"touchLetter": "Z","img1":"assets/icons/letters/D.png","img2":"assets/icons/letters/Z.png","img3":"assets/icons/letters/O.png"},
  {"touchLetter": "B","img1":"assets/icons/letters/B.png","img2":"assets/icons/letters/Q.png","img3":"assets/icons/letters/L.png"},
  {"touchLetter": "G","img1":"assets/icons/letters/G.png","img2":"assets/icons/letters/S.png","img3":"assets/icons/letters/T.png"},
  {"touchLetter": "X","img1":"assets/icons/letters/L.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/X.png"},
  {"touchLetter": "R","img1":"assets/icons/letters/R.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/O.png"},
  {"touchLetter": "P","img1":"assets/icons/letters/A.png","img2":"assets/icons/letters/P.png","img3":"assets/icons/letters/C.png"},
  {"touchLetter": "K","img1":"assets/icons/letters/B.png","img2":"assets/icons/letters/E.png","img3":"assets/icons/letters/K.png"},
  {"touchLetter": "Q","img1":"assets/icons/letters/F.png","img2":"assets/icons/letters/Q.png","img3":"assets/icons/letters/D.png"},
  {"touchLetter": "L","img1":"assets/icons/letters/L.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/B.png"},
  {"touchLetter": "O","img1":"assets/icons/letters/Z.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "T","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "W","img1":"assets/icons/letters/W.png","img2":"assets/icons/letters/G.png","img3":"assets/icons/letters/X.png"},
  {"touchLetter": "Z","img1":"assets/icons/letters/P.png","img2":"assets/icons/letters/Z.png","img3":"assets/icons/letters/N.png"},
  {"touchLetter": "J","img1":"assets/icons/letters/H.png","img2":"assets/icons/letters/I.png","img3":"assets/icons/letters/J.png"},
  {"touchLetter": "B","img1":"assets/icons/letters/K.png","img2":"assets/icons/letters/B.png","img3":"assets/icons/letters/L.png"},
  {"touchLetter": "H","img1":"assets/icons/letters/H.png","img2":"assets/icons/letters/D.png","img3":"assets/icons/letters/M.png"},
  {"touchLetter": "S","img1":"assets/icons/letters/S.png","img2":"assets/icons/letters/O.png","img3":"assets/icons/letters/N.png"},
  {"touchLetter": "U","img1":"assets/icons/letters/N.png","img2":"assets/icons/letters/P.png","img3":"assets/icons/letters/U.png"},
  {"touchLetter": "M","img1":"assets/icons/letters/Z.png","img2":"assets/icons/letters/M.png","img3":"assets/icons/letters/P.png"},
  {"touchLetter": "A","img1":"assets/icons/letters/L.png","img2":"assets/icons/letters/A.png","img3":"assets/icons/letters/W.png"},
  {"touchLetter": "Y","img1":"assets/icons/letters/Y.png","img2":"assets/icons/letters/U.png","img3":"assets/icons/letters/V.png"},
  {"touchLetter": "E","img1":"assets/icons/letters/V.png","img2":"assets/icons/letters/Q.png","img3":"assets/icons/letters/E.png"},
  {"touchLetter": "P","img1":"assets/icons/letters/P.png","img2":"assets/icons/letters/T.png","img3":"assets/icons/letters/Z.png"},
  {"touchLetter": "V","img1":"assets/icons/letters/R.png","img2":"assets/icons/letters/V.png","img3":"assets/icons/letters/N.png"},
  {"touchLetter": "X","img1":"assets/icons/letters/W.png","img2":"assets/icons/letters/S.png","img3":"assets/icons/letters/X.png"},
  {"touchLetter": "I","img1":"assets/icons/letters/I.png","img2":"assets/icons/letters/B.png","img3":"assets/icons/letters/P.png"},
  {"touchLetter": "F","img1":"assets/icons/letters/X.png","img2":"assets/icons/letters/F.png","img3":"assets/icons/letters/F.png"},
];